[package]
name = "hrx-get"
description = "Reader for Human Readable Archive (.hrx) data"
version = "0.1.2"
authors = ["Rasmus Kaj <kaj@kth.se>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/kaj/hrx-get"
readme = "README.md"
edition = "2018"

[dependencies]
